### ISSUE TITLE
Filtering by new pages doesn’t work

### ISSUE THREAD

**Issue by stjohann** [stjohann/DiscordWikiBot#1]
DiscordWikiBot uses [XmlRcs](https://github.com/huggle/XMLRCS/tree/master/clients/c%23/XmlRcs) to stream recent changes to Discord servers. With the new filtering options, I wanted to provide an ability to filter by new pages only. Right now, it doesn’t work.

In my testing, `huggle-rc.wmflabs.org` didn’t respond with *any* events that matched `ChangeType.New`, no matter how I’ve written the relevant code. I haven’t done thorough investigation, but for now everything suggests that the problem is upstream. I’ve tried to reach out to Huggle devs that have written that helpful library but haven’t got a response yet.

Relevant code:
- https://github.com/stjohann/DiscordWikiBot/tree/master/DiscordWikiBot/XmlRcs
- https://github.com/stjohann/DiscordWikiBot/tree/master/DiscordWikiBot/EventStreams.cs#L176

Phabricator issue:
https://phabricator.wikimedia.org/T220856

**Comment by benapetr** [comment]
Hello,

I will have a look in that but as far as I know XmlRcs should definitely report new pages as well

**Comment by benapetr** [comment]
This is Huggle's internal code for processing of XmlRcs feed: https://github.com/huggle/huggle3-qt-lx/blob/master/src/huggle_core/hugglefeedproviderxml.cpp#L313

You can see there that edit has attribute type which contains at least values "edit" and "new" (maybe even some other values?) new stands for a new page, edit is an edit to existing page.

I will check how is this implemented inside of C# library

**Comment by benapetr** [comment]
But yeah after quick test it seems that upstream indeed doesn't send any new pages. Something must have changed on Event Streams side.

There is this python code that fetches the changes from ES: https://github.com/huggle/XMLRCS/blob/master/src/es2r/es2r.py

It's no longer obtaining any new pages, not sure why is that.

**Comment by stjohann** [comment]
Fixed in huggle/XMLRCS@414512851d4a73c0b2afdbec174725bbd54d8078 as confirmed in my test runs. Thank you for your help, @benapetr
