### ISSUE TITLE
WikiBot does not work in Text Chat in Voice Channels

### ISSUE THREAD

**Issue by AntiCompositeNumber** [stjohann/DiscordWikiBot#22]
WikiBot does not appear to work with this feature: https://support.discord.com/hc/en-us/articles/4412085582359

**Comment by stjohann** [comment]
If I read it correctly, DSharpPlus/DSharpPlus#1149 implemented this in upstream library. If I get to it, this should just involve updating library to a nightly version and checking that everything still works. If I don’t get to it in time, the same but with a stable version.

**Comment by AntiCompositeNumber** [comment]
Any chance you'll be able to do this soon?

**Comment by stjohann** [comment]
Tested that it works on my end, so I guess done. Going to update the WikiBot instance soon.
