### ISSUE TITLE
Ignore magic words when linking to templates

### ISSUE THREAD

**Issue by stjohann** [stjohann/DiscordWikiBot#5]
There are MediaWiki APIs that can return a list of all magic words and parser functions in a wiki. While we already ignore parser functions (since `#` at the start can’t denote a template), magic words sometimes get linked by people. It is better to ignore these when they are written like `{{BASEPAGENAME}}`, but still allow them when someone explicitly writes `[[Template:BASEPAGENAME]]`.

~~[CXuesong/WikiClientLibrary](https://github.com/CXuesong/WikiClientLibrary) doesn’t have an interface for getting this information, so we will need to do separate API requests.~~ https://github.com/CXuesong/WikiClientLibrary/issues/89 added SiteInfo.MagicWords that can be used here in some way.

Example of an API response:
https://ru.wikipedia.org/w/api.php?action=query&meta=siteinfo&siprop=magicwords|variables&formatversion=2

**Comment by jhsoby** [comment]
Here as well, see how I solved this very problem in [this commit](https://github.com/jhsoby/telegram-wikilinksbot/commit/8abfaf2e8f88e2b7c77896612659b5d10ff3c357). :grin:

**Comment by stjohann** [comment]
> Here as well, see how I solved this very problem in [this commit](https://github.com/jhsoby/telegram-wikilinksbot/commit/8abfaf2e8f88e2b7c77896612659b5d10ff3c357). 😁

I opted for a different API endpoint in the end, since I need it to have localised values, too (subst: can be подст: in Russian etc.). Either way, MediaWiki has several flaws with all of them, since you cannot actually differentiate between parser functions with `#` and without it reliably. Still, any solution with some false positives will be better than nothing.
